### PR TITLE
bigiddatadiscovery: New App - initial release

### PR DESCRIPTION
**Pull request by dcoleman2**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by dcoleman2** [comment]
Added `# nosemgrep` for false positive in `bigid_proxy.refresh_token`. Was incorrectly flagged as including tokens/secrets in url.

**Review by dcoleman2 — COMMENTED** [review]
hi @ighelani-crest , can you please explain what these changes are and why they were made?

[95b2c0b](https://github.com/splunk-soar-connectors/bigiddatadiscovery/pull/1/commits/95b2c0bc56474550b0f2d409601a555a49727e41)

**Comment by ighelani-crest** [comment]
Hi @dcoleman2,
I have done these changes related to the best practices that we follow. I have updated the publisher to its previous value. As per our standard, the min_phantom_version should be 5.5.0. Can you please test your app on 5.5.0 and update the min_phantom_version?

**Comment by dcoleman2** [comment]
Thanks @ighelani-crest ... will work on getting our dev environment upgraded for testing.

Any thoughts/guidance on the remaining violations for the static tests?

- repo_name_has_expected_app_id
  - "message": "Could not find an app id for bigiddatadiscovery. Please add the app id for bigiddatadiscovery to data/repo_name_to_appid.json"
- document_commonly_used_service_ports
  - "message": "Matched regex 'BigID|Data|Discovery|Foundation' (510 times) using app's name/product_name json fields in local copy of iana common service ports file. (See https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml) Please check if this app requires specific ports open on Phantom instance and add to app's documentation."

**Comment by ighelani-crest** [comment]
hi @dcoleman2 ,
it is due to the local repo check that we maintain, I have raised the PR for that failures will be resolved once it is merged!

**Comment by ighelani-crest** [comment]
Hi @dcoleman2,
Have you tested your app on 5.5.0 instance ?
so that we can change min_phantom_vesion and proceed with release.
Thanks !!

**Comment by ighelani-crest** [comment]
Hi @dcoleman2,
can you please let me know why you have closed the PR?
are you planning to raise the new PR with more features or something else?

**Comment by dcoleman2** [comment]
Hi @ighelani-crest ,  I am no longer associated with BigID. Any follow up related to this PR, etc. will have to be coordinated with them.

**Pull request closed without merging**
